baseURL = 'https://palza4dev.github.io'
languageCode = 'en-us'
title = 'Hey !! this is title'
theme = 'PaperMod'
googleAnalytics = 'G-T68TSV1RG4'
shortname = "devblog-gdzaz0odmp"

[params]
comments= true