baseURL = 'https://palza4dev.github.io'
languageCode = 'en-us'
title = 'Mooner'
theme = 'PaperMod'

googleAnalytics = 'G-T68TSV1RG4'

disqusShortname = "devblog-gdzaz0odmp"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"

# robots.txt
enableRobotsTXT = true

# sitemap 생성
[sitemap]
# always, hourly daily, weekly, monthly, yearly, never
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
  
[params]
env = 'production'
comments = true
description = "Mooner's dev blog"

ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowToc = true
TocOpen = true
ShowBreadCrumbs = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 5

# [[menu.main]]
# identifier = "categories"
# name = "Categories"
# url = "/categories/"
# weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/palza4dev"
weight = 30
