baseURL = 'https://palza4dev.github.io'
languageCode = 'en-us'
title = 'Hey !! this is title'
theme = 'PaperMod'
googleAnalytics = 'G-T68TSV1RG4'

[params.page.comment]
      enable = true
      [params.page.comment.disqus]
        enable = true
        shortname = "devblog-gdzaz0odmp"