baseURL: https://palza4dev.github.io
languageCode: en-us
title: Mooner
theme: PaperMod

googleAnalytics: G-T68TSV1RG4

disqusShortname: devblog-gdzaz0odmp

enableRobotsTXT: false
# sitemap:
#   changefreq: daily
#   filename: sitemap.xml
#   priority: 0.5

taxonomies:
  author: authors
  category: categories
  tag: tags
  series: series

params:
  env: production
  comments: true
  description: Mooner's dev blog
  ShowFullTextinRSS: true
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: false
  hidemeta: false

  homeInfoParams:
    Title: Hi there
    Content: Can be Info, links, about...

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content

assets:
  disableHLJS: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: archive
      name: Archives
      url: /archives/
      weight: 5
    - identifier: series
      name: Series
      url: /series/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 15
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    # - identifier: github
    #   name: Github
    #   url: "https://github.com/palza4dev"
    #   weight: 30
