baseURL: "https://palza4dev.github.io"
languageCode: en-us
title: Mooner
theme: PaperMod
googleAnalytics: G-T68TSV1RG4
disqusShortname: devblog-gdzaz0odmp
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
taxonomies:
  author: authors
  category: categories
  tag: tags
  series: series
params:
  assets:
    disableHLJS: true
  env: production
  comments: true
  description: Mooner's dev blog
  ShowFullTextinRSS: true
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: series
      name: Series
      url: /series/
      weight: 5
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: github
      name: Github
      url: "https://github.com/palza4dev"
      weight: 30
